### ISSUE TITLE
camera_window_test.py doesn't work

### ISSUE THREAD

**Issue by GDelevoye** [MyreMylar/pygame_gui_examples#8]
Hello, one of the example doesn't work

I don't have time to debug it or to make a PR so I'll just report here:

```console
guillaume@A320MA:~/GitHub/pygame_gui_examples$ python camera_window_test.py 
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "camera_window_test.py", line 69, in <module>
    CameraWindow(cam_window_rect, cam_id, cam_names[cam_id], manager)
  File "camera_window_test.py", line 30, in __init__
    self.camera = pygame.camera.Camera(camera_id, (160, 120))
TypeError: argument 1 must be str, not int
```

**Comment by MyreMylar** [comment]
The camera works as far as I can tell.
